---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by JiaHaowei.
--- DateTime: 2026/9/30 20:26
---

--- 比较线程标示与锁中的标示是否一致
if (redis.call('get', KEYS[1]) == ARGV[1] ) then
    ---释放锁
    redis.call('del',KEYS[1])
end
return 0